title: <p align="center"> Sonipriya Singh</p>
logo: sonipriya.jpeg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sonipriya-singh-317a1a116/">LinkedIn</a> |
  <a href="https://github.com/spsingh3">GitHub</a>
  
  <br>   
  I'm currently working in EDA industry as a software developer.
  Working in EDA domain for 7 years
  <br>
  </p>



theme: jekyll-theme-minimal
